---
- name: Packages
  include_tasks: packages.yaml

- name: Network
  include_tasks: network.yaml

- name: User
  include_tasks: user.yaml

- name: SSH
  include_tasks: ssh.yaml

- name: fail2ban
  include_tasks: fail2ban.yaml

- name: logrotate
  include_tasks: logrotate.yaml