---
servers:
  vars:
    docker_user: dylan
    ansible_user: dylan
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
  children:
    proxmox:
      hosts:
        pve-01:
          ansible_host: 10.1.10.51
          corosync_ips: 10.54.0.51
          # ceph_network_ip: 10.55.0.51
          ansible_python_interpreter: /usr/bin/python3
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          cpu_type: intel
          iommu_config: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt"'
          bootmgr: grub
          raw_disks:
            - /dev/sdc
            - /dev/sdd
          kubernetes_vm_ids:
            - 333

        pve-02:
          ansible_host: 10.1.10.52
          corosync_ips: 10.54.0.51
          # ceph_network_ip: 10.55.0.52
          ansible_python_interpreter: /usr/bin/python3
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          iommu_config: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt"'
          bootmgr: grub
          kubernetes_disks:
            - /dev/disk/by-id/ata-CT1000BX500SSD1_2303E6A11C03
            - /dev/disk/by-id/ata-CT1000BX500SSD1_2303E6A11D6E
          kubernetes_vm_ids:
            - 334

        pve-03:
          ansible_host: 10.1.10.53
          corosync_ips: 10.54.0.51
          ansible_python_interpreter: /usr/bin/python3
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          iommu_config: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet amd_iommu=on iommu=pt"'
          bootmgr: grub
          kubernetes_disks:
            - /dev/disk/by-id/ata-CT1000MX500SSD1_2303E69F5D13
            - /dev/disk/by-id/ata-CT1000MX500SSD1_2303E69F5A5D
          kubernetes_vm_ids:
            - 335

    pxe:
      hosts:
        netboot-srv-01:
          ansible_host: 10.1.30.5
          ansible_user: dylan
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python3
          ansible_become: true
