- name: Create netbootxyz directory
  file:
    path: /opt/netbootxyz
    state: directory
    owner: dylan
    group: docker
    mode: "0755"
  become: true

- name: Create netbootxyz config directory
  file:
    path: /opt/netbootxyz/config
    state: directory
    owner: dylan
    group: docker
    mode: "0755"
  become: true

- name: Create netbootxyz assets directory
  file:
    path: /opt/netbootxyz/assets
    state: directory
    owner: dylan
    group: docker
    mode: "0755"
  become: true

- name: Install netboot.xyz compose file
  template:
    src: files/docker-compose.yaml
    dest: /opt/netbootxyz/docker-compose.yaml
    mode: "0644"
    owner: dylan
    validate: docker-compose -f %s config
  register: compose_file
  become: true

- name: restart netboot.xyz
  shell:
    chdir: /opt/netbootxyz
    cmd: docker compose restart netbootxyz
  when: compose_file.changed
