---
- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
  become: yes

- name: restart adguardhome
  systemd:
    name: AdGuardHome
    state: restarted
  become: yes
