---
- name: Reboot Raspberry Pi Servers
  hosts: all
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Reboot all pi4 servers
      reboot:
        reboot_timeout: 3600
