- name: remove immutable flag from /etc/resolv.conf
  command: chattr -i /etc/resolv.conf
  ignore_errors: true

- name: Replace /etc/systemd/resolved.conf
  copy:
    src: files/resolved.conf
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: 0644

- name: remove old /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

- name: symlink /etc/resolv.conf to /run/systemd/resolve/resolv.conf
  command: ln -sv /run/systemd/resolve/resolv.conf /etc/resolv.conf

- name: restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted
    enabled: yes

- name: Check if machine is cloudinit
  stat:
    path: /etc/cloud/cloud.cfg
  register: cloud_cfg

- name: Copy over new cloud.cfg
  copy:
    src: files/cloud.cfg
    dest: /etc/cloud/cloud.cfg
    owner: root
    group: root
    mode: 0644
  when: cloud_cfg.stat.exists
