---
- name: Longhorn Setup
  block:
    - name: Check for /var/lib/longhorn
      stat:
        path: /var/lib/longhorn
      register: longhorn_lib

    - name: Remove directory (var/lib/longhorn)
      file:
        path: /var/lib/longhorn
        state: absent
      when: longhorn_lib.stat.exists

    - name: Check and unmount longhorn directory
      block:
        - name: Check for longhorn directory mount point
          stat:
            path: "{{ longhorn_mount_point }}"
          register: longhorn_dir

        - name: Unmount longhorn directory
          mount:
            path: "{{ longhorn_mount_point }}"
            state: unmounted
          when: longhorn_dir.stat.exists

    - name: Clean disks and format + mount
      ignore_errors: true
      when: ssd_disks | default([]) | length > 0
      block:
        - name: wipe (wipefs)
          command: "wipefs -a {{ ssd_disks }}"

        - name: wipe (sgdisk)
          command: "sgdisk --zap-all {{ ssd_disks }}"

        - name: wipe (dd)
          command: "dd if=/dev/zero of={{ ssd_disks }} bs=1M count=100 oflag=direct,dsync"

        - name: format disks ext4
          filesystem:
            fstype: ext4
            dev: "{{ ssd_disks }}"

    - name: Get UUID of disks (blkid)
      command: "blkid -s UUID -o value {{ ssd_disks }}"
      register: blkid

    - name: Check for Mount Point
      stat:
        path: "{{ longhorn_mount_point }}"
      register: mount_point

    - name: Create mount point for longhorn
      when: not mount_point.stat.exists
      file:
        path: "{{ longhorn_mount_point }}"
        state: directory
        mode: 0755

    - name: Mount the disks to the longhorn mount point
      mount:
        path: "{{ longhorn_mount_point }}"
        src: "UUID={{ blkid.stdout }}"
        fstype: ext4
        state: mounted
        opts: defaults

    - name: Apply Label to nodes (longhorn)
      command: "kubectl label node --overwrite {{ inventory_hostname }} node.longhorn.io/create-default-disk=true"
