---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn-recurring-jobs
spec:
  chart:
    spec:
      chart: longhorn-recurring-jobs
      version: 5.0.2
      sourceRef:
        kind: HelmRepository
        name: tyzbit
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  interval: 1h
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    createStorageClasses: true
    storageclass:
      # -- Default StorageClass properties.
      allowVolumeExpansion: true
      reclaimPolicy: Retain
    groups:
      # Quoting isn't required, but improves readability
      "Config":
        options:
          storageclass:
            # You may override these properties for the storage classes for this group
            # This only takes effect if createStorageClasses is true
            allowVolumeExpansion: true
            reclaimPolicy: Delete
          # You can specify longhorn-specific parameters under this key
          parameters:
            replicaAutoBalance: "best-effort"
            dataLocality: "best-effort"
            numberOfReplicas: "2"
            staleReplicaTimeout: "30"
        # At least one task type is required.
        snapshot:
          - interval: 10m
            retain: 6
            # You may override the defaultConcurrency on each interval specification
            concurrency: 10
        backup:
          - interval: 1h
            retain: 5
          - interval: 6h
            retain: 4
        snapshot-cleanup:
          # retain is unnecessary for snapshot-cleanup and snapshot-delete, it is ignored.
          - interval: 1h
        snapshot-delete:
          - interval: 1h
