---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age109xxk5j8q09kprdd5wta9fw7nwpz8t95phq49eclrefjy3zjncmqa9lgtk"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age109xxk5j8q09kprdd5wta9fw7nwpz8t95phq49eclrefjy3zjncmqa9lgtk"
stores:
  yaml:
    indent: 2
