---
services:
  op-connect-api:
    image: 1password/connect-api:latest
    ports:
      - 80:8080
    volumes:
      - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
    networks:
      container_lan:
        ipv4_address: 10.1.33.90

  op-connect-sync:
    image: 1password/connect-sync:latest
    ports:
      - 8081:8080
    volumes:
      - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
    networks:
      container_lan:
        ipv4_address: 10.1.33.90
network:
    container_lan:
      driver: ipvlan
      driver_opts:
        parent: mainif.33
      ipam:
        driver: default
        config:
          - subnet: 10.1.33.0/24
            gateway: 10.1.33.1
            ip_range: 10.1.33.90/32
volumes:
  data: