---
- name: Ensure sudo group is present
  group:
    name: sudo
    state: present
  become: true

- name: Ensure sudo group has sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) ALL NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"


- name: Create default user
  user:
    name: "{{ me.user }}"
    groups: sudo
    password: ""
    shell: /bin/bash
    state: present

- name: User | Remove old user
  user:
    name: "{{ me.old_user }}"
    state: absent

- name: User Configuration | SSH keys
  authorized_key:
    user: "{{ me.user }}"
    key: "https://github.com/DylansDecoded.keys"
    state: present

- name: User Configuration | Grant ownership of {{ me.user }} home directory
  file:
    path: "/home/{{ me.user }}"
    owner: "{{ me.user }}"
    group: "{{ me.user }}"
    state: directory
    recurse: yes

