---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2024.3.0@sha256:cb78a75b991b1d90a0d86d0003c605882c0a19961546faa7a0f8da34a942bc1a
            env:
              TZ: America/New_York
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 1Gi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: 8123
    ingress:
      app:
        enabled: true
        className: external
        annotations:
          # gethomepage.dev/enabled: "true"
          # gethomepage.dev/name: "Home Assistant"
          # gethomepage.dev/group: Home Automation
          # gethomepage.dev/icon: "home-assitant.png"
          # gethomepage.dev/widget.type: "homeassistant"
          # gethomepage.dev/widget.url: https://hass.robsonhome.cloud
          external-dns.alpha.kubernetes.io/target: external.robsonhome.cloud
        hosts:
          - host: &host hass.robsonhome.cloud
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant
      tmp:
        type: emptyDir
