---
- name: Mask systemd-network-wait-online
  command: systemctl mask systemd-networkd-wait-online

- name: Enable systemd-networkd
  systemd:
    name: systemd-networkd
    state: started
    enabled: true

- name: Find netplan config
  find:
    paths: /etc/netplan
    patterns: "*.yaml"
  register: netplan_old

- name: Remove old netplan
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ netplan_old.files }}"

- name: Configure netplan
  template:
    src: templates/01-netplan-all.yaml.j2
    dest: /etc/netplan/01-netplan-all.yaml

- name: Apply netplan
  command: netplan apply

- name: Restart networkd
  systemd:
    name: systemd-networkd
    state: restarted

- name: Delete /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

- name: Disable systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Update /etc/resolv.conf
  copy:
    dest: /etc/resolv.conf
    content: |
      nameserver {{ ansible_default_ipv4.address }}
    mode: preserve
