---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: v1.5.3
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
    annotations:
      prometheus.io/scrape: "true"
    defaultSettings:
      defaultDataPath: /mnt/longhorn/
      backupTarget: s3://longhorn@us-east-1/backups
      backupTargetCredentialSecret: longhorn-backup-secret
      defaultReplicaCount: 2
      createDefaultDiskLabeledNodes: true
      restoreVolumeRecurringJobs: true
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 1
      guaranteedEngineManagerCPU: 20
      guaranteedReplicaManagerCPU: 20
      orphanAutoDeletion: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      defaultLonghornStaticStorageClass: longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    ingress:
      enabled: true
      ingressClassName: internal
      host: &host longhorn.robsonhome.cloud
      tls: true
      tlsSecretName: *host
      secureBackend: true
