---
- name: Create nginx-proxy-manager directory
  file:
    path: "/home/{{ me.user }}/npm"
    state: directory
    owner: "{{ me.user }}"
    group: "{{ me.user }}"

- name: Copy docker-compose.yaml
  copy:
    src: files/docker-compose.yaml
    dest: "/home/{{ me.user }}/npm/docker-compose.yaml"
    owner: "{{ me.user }}"
    group: "{{ me.user }}"
# - name: start nginx proxy manager
#   command: docker-compose up -d
#   args:
#     chdir: "/home/{{ me.user }}/npm"
