# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: qbtools-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:HGNozIDFwipRANj0aJYOPzjjFWn/hwtjuJ7ywJ1iljNajiNUgLaC3xkmsH8QRAI9Fc/yPME51FU+Ijpz1kqhyRCUEVhMUPbfULPU/Msa2C4PZswRDmDUCOha1Xvpn5iRzpZjJuNq1gmRyQFLb0oyNmGYoE0ty+am1Kq80Qn6yTsePKRNi4OF7muTWvB45tPbEG7HmwwmhHrmEBtHI+IbtKovi6K02xBbT/GyGjwzd1gWBxYacoQVUE4I5WeAe0mDEg0y6T+kQOFHmv7uWLi8+UTcfsg/GtImAsJiBouLYnwDwvK3ysOoXZx4W+mdnmuJ5/uj5LqKUqWeDM4pGXB89LpAdR5/3iC5ljTaNhkipqAbTjioZH93BAUSGFi8rcNI9C3KaHxkO0osiJ6MKpHfMZDJ+FAv7m5x+mrBXJD11C2pK5SpDgL0UPIhIAXuAOfSGnj6i81Rki+X/UcJaB3Ic516sg/4Fao+CdmidZwLR04+C2aQDd6C+XDJlhDN8O/jrZRPd7+jBRzLhofqfAhANK5qY01kIszrkK7JSRhD2IoiKe/Uc+kgfSD9Cs27prS3F2LuUZlRY1MqV3bGTKuJlOjRMm9VBPA1D+JShtBqv1kg5/BXU+oFGIP+E1wIngNDVEpHRmmIu3uPJZ08Jtf8vN3/q00gssxhnZEy5qVzmvTSkQUpzw/0CpG2mbBg3zs8z7q9JGPeAl1ZA7ocEonyhmqhx7td0VMQOBuGet+DSu3iapUDPSplugssRBF5nF4U3RKRThfBvc/x9+yLN9uvdTkstI2sG9hOw3AoCxbqTWEyeNWDtl6scOHL/bWGFBjEz1UY5losCz1Zgp8U677INEyurpcvL71Bwc256YJLqQ0kqjjMJ5mTLrFGJrWt4CX9QsdctGpv9Rx7yI82u2VYFFwh6hgWk7TeNJ03RhQ35tExG4WbEo5XXBEMHXT5SB5ysnQ6M9sgtT2NFpe/wN/vXifE+ZOwUMERKewv5ENth5JCMxk5iUU/W3XS40TGObUZoYniv0v5cQZ3FrT1z3POKt4IXL0aTB0K2ZAPdSPHAxmQv6qqZ0LACkz5790iNH6DthZe8IjKXFozW6eBOaiLmupr/iIzvkAV5QzKqZXU2RmY8bhVs3HUfZmSgJ/gHh9UlmZ4aj/wpyTnZp9ytO+m1b0L4CI2Lqd002nylvxSvEVCApvNgf0YaDej8Urc/3b0/FDLly8xy4wPvDtnI1SxuHwmA+1xInsbeY/W7APvlDkfXO08xs+P4p1SFxFzBgbuZBvkE4vVq6d2wO8E9BO2MhQZEgJQ3zwMSiYTZ5G4bh1o8Qem6Rkfw4OmeLfCqWDT,iv:YSK0wKzWQdXcG0xTsE8iEzq1dZwBcizCGJzGbWKZI/I=,tag:ZJbZU0HHo+mSRlEf68kdTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2rgupgcxr8d4mf9jf5rgm8cetz9utdvv9dzqk09y0f4c08zyvdsdw8h2v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWmY5S3N4bU5wQmFKaFRP
            c2JGdTBDVzY1eFEvNjltaWE0N1hZcktrL21NCmJGNjdjaHZVY1pKTFQ5ZnZwVEhl
            Z0g1MFRZcEdqUGd6YSswTGI2c2l5N3cKLS0tIEVBTXZDVVBlVVp0RGpPUjNIanVx
            MU1vNXZtUFdQRW9ramRFZkJYc1BnSVkKu92Xppiyf8+j5I0PAdvwrtI1M8EaQvNq
            s0ZE/nNlIhKPnGUOdnM7D8pYehJZGRp5fHlLFA1t44rfQOjeAFGvSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-03T00:50:15Z"
    mac: ENC[AES256_GCM,data:eNSxPJTuQ9urUt/qVtOWVyFQx/7fUXNzAVab7fzvsjAQkO3T98IvjAzYNd8XDp6lfJu2nzZY43e+tVsZ+EYzoJod4kRoWlH3zYjag8nBW0DnqXIzDjM7cpAfVjHTCG45c5bFi6vBLL0ORWlltlXRqTk/BFWeGLy6SSSlzilmDZw=,iv:eKj+vQ7yhZ+lKvNXl7erGiOnwyl/H7BOUb5LL5CW/VM=,tag:dE56umai6VQW3xEMuFcdkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
