# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: qbtools-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:W9i/uUcFWtHvQ0WvpX3heFFjCsLenPDSJK9RNdFaOBl2TCIpCW+amk3dOnqO8AH2BelEwOizYDXUFYXVmgS8HvcGAWvb5sr7AglnVfTqtTiI01FMYUY4AM/8/KimCzIgbRQ0Oyekofigj4YS99dm0PTeCtTfgtIR3mzxdvZEaoXWtqaZcyW1GHZ14iQhPprXcOo/yaEr2DUv3G0xiZpFod+TkOPPIlhOHSMdSUVKVZOzxN7aY+C31D9W+ojkcSDsUI3wLfsJSWp5fm7FqQZbUruXpahxGPS2T3OKH4vXFbebfcZVkRKi6Ck6HACj0s0dAlKM+sg9OKkV4Uz9Ci4M+rXOi+ouyky2rk6O16vGeTTS+dYcGV5JjyLWCm3aXnhggJvtcEv5CPX0VWtZzI9k1/xHC/tFOLE1y96LKwMLNFI9P5G9+frv5EXRKLkk22TkjrMaoSb/aKwmy3qBH8VqZQYAm63tKntVVGl46P5pB3stpVG9Yghd0zB1BYw+V813/5pzQTqfrvxIqezSiNtUADXJV2MsrswTEnoGi+un8yVM2zgffa0xMtgeSk5+DZQjejhriVQGygZYmUqrRQps7dw8N+mGi8RzdtsPzBOFsIiBcBDwAR6yuU0lZHgjSmhKJdQfPEDbsqjA40Xw2oq+TR0gHLRnR0urRHnlx2N44mqhkl4OzlO91Xg47+f8AAZHsAWPvLN/PUPn6Ys85nqX7sDP3pRNtoRC/J3eUIKbEhcY3UbsOITtmUQse6vupIRzup+0AhIcuMkkQXOzTDFSA3nhu5R6atE2tMZ7GUF1WurKhNxSN5XdliX1UgiJ/3Kwz/AoU7y4LKiqjewrHvdabrOkUVj20uX7q+4qOuL9ZiYLhFzrV9xZ0NybzG+Nlrz1L4894kp6iB+264L+52XbQdlLefgBZCaVfa4FaRJ8TaAZKhVic9FWhtr5Rh4ea0dlpUB8IhUIayG+u0za80eNRAZ36WRAwpR8a/4QVPgo18fuMAKldgHzmoIg1NiXrd8egxLGD2Arun9hVBpaa0bmNLX01rUcKCh+mcC18XEvdbqrbGoJzyklVvw29ZWo/ZRGLP1c12g3Sb3Hsw7WIDoBLNiIHSMwrFWfgRsLNXqBqTQ1dRWiRBuqPYkvioUQ/CT/b3A8fLD9wzneCJ7GPIsjnLKbkeVvMT5MgGdcjOt8oG16fDPlNiQPKQifIJqtaO1nhEKa/EAyOeo6aQe9wsIOqG9tEY4pLKMJEbwgPkG1NhugH6GSMwb+m988lLmQ8hhkg1hVq/eD4qXL3Q1OPIOsfVPm6lQXg1190duBzJDMK3ysjvG75R2l4a1Jp3oG9awzb5nu99Hnenz+jRvPP08OY7zmbmufOSs6cP79MYgqIJk9cp593zxKifrAD1pL7i7jaTMz05B5eMGQU/YQTFWoiZ4hmedv7u765mEbzodcuX8V15TUFh6XhrpV98IV/mmJejd6PS4B8A==,iv:ixBWrX7allwjU2s3i7SkwGScXq7EdmXSCm33/mdLDys=,tag:S0uX14e+WixwUTbGSQr0vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2rgupgcxr8d4mf9jf5rgm8cetz9utdvv9dzqk09y0f4c08zyvdsdw8h2v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZTZHU2Mzc2REZDFQU1Yw
            a09RZmNQNHNFczM3OGxvVytIQVo3TkZ6Z2tBClUyZ1I1VnV0UHkyU3lmTGFjNFZq
            UGw5WkhkMnErMXJqQWJkaEVoZHpZZDAKLS0tICtld2pnZEU5Z3IxNTVRMUkzM3Fj
            VW5WbDlzaTBCbWZCL1FDOFUvNUgzeUkKOOmNXqXiE0TyEgW21jB13awlbA6fzzg4
            b6XH4ri1UJOlp0odwOzgFuIbA51ODe6qp/Qwbh9attu+Sh5mu8Fo2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-23T01:13:50Z"
    mac: ENC[AES256_GCM,data:VAFs9N6xpKWJDsCKhwdzJX8TVsig5UOIpqfQiS0D6jOzL6O4xBIiUSHvKxNrgiHd42laxBcUvfvjZoZoCn6p65J9Qv5bmCS6WeHEjHtG2qXGDpKClJBjhObLrR6dvCNJ57RXWOgxaZ565blKg6Qm23bQ9iB0bTiBlUPvt5r3ZYI=,iv:TjhG2vBMlBIgsrGeqElhClBdN6y1DOSXAQO1Hnojc6w=,tag:rtPos43IwzkHRxp9sGYWkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
