kubernetes:
  vars:
    ansible_user: dylan
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
    longhorn_mount_point: /mnt/data

  children:
    master:
      hosts:
        k3s-pi4-master-01:
          ansible_host: 10.1.30.30

        k3s-pi4-master-02:
          ansible_host: 10.1.30.31

        k3s-pi4-master-03:
          ansible_host: 10.1.30.32

    worker:
      hosts:
        k3s-pve-worker-01:
          ansible_host: 10.1.30.34

        k3s-pve-worker-02:
          ansible_host: 10.1.30.35

        k3s-pi4-worker-01:
          ansible_host: 10.1.30.36

        k3s-pi4-worker-02:
          ansible_host: 10.1.30.37

    longhorn_nodes:
      hosts:
        k3s-pve-worker-01:
          ssd_disks: /dev/sdb
          ansible_host: 10.1.30.34

        k3s-pve-worker-02:
          ssd_disks: /dev/sdb
          ansible_host: 10.1.30.35

        k3s-pi4-worker-01:
          ssd_disks: /dev/sda
          ansible_host: 10.1.30.36
