---
- name: Configure Default User
  block:
    - name: Create the default user
      user:
        name: "{{default_user}}"
        shell: /bin/bash
        password: "{{default_user_password}}"
        groups: sudo
        append: yes
        createhome: yes
        home: "/home/{{default_user}}"
        state: present

    - name: Grant Full Permissions to home directory
      command: "chown -R {{default_user}}:{{default_user}} /home/{{default_user}}"

    - name: Ensure default user has sudo access without password
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^{{default_user}} ALL=(ALL) NOPASSWD: ALL$"
        line: "{{default_user}} ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"
        backup: yes

    - name: Create the .ssh directory
      command: "mkdir -p /home/{{default_user}}/.ssh"

    - name: Create the authorized_keys file
      command: "touch /home/{{default_user}}/.ssh/authorized_keys"

    - name: Copy authorized keys
      copy:
        src: files/ssh/authorized_keys
        dest: "/home/{{default_user}}/.ssh/authorized_keys"
        owner: "{{default_user}}"
        group: "{{default_user}}"
