---
- name: Configure SSH
  block:
    - name: Copy sshd_config
      template:
        src: templates/sshd_conf.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644

    - name: Restart sshd service
      service:
        name: sshd
        state: restarted
        enabled: yes
