---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
    template:
      engineVersion: v2
      data:
        # PLUS_API_KEY: "{{ .FRIGATE_PLUS_API_KEY }}"
        REOLINK_DRIVEWAY_FLOODLIGHT_CAM_FFMEPG_MAIN: "{{ .REOLINK_DRIVEWAY_FLOODLIGHT_CAM_FFMEPG_MAIN }}"
        REOLINK_DRIVEWAY_FLOODLIGHT_CAM_FFMEPG_SUB: "{{ .REOLINK_DRIVEWAY_FLOODLIGHT_CAM_FFMEPG_SUB }}"
        REOLINK_BACKPORCH_TURRET_CAM_FFMEPG_MAIN: "{{ .REOLINK_BACKPORCH_TURRET_CAM_FFMEPG_MAIN }}"
        REOLINK_BACKPORCH_TURRET_CAM_FFMEPG_SUB: "{{ .REOLINK_BACKPORCH_TURRET_CAM_FFMEPG_SUB }}"
        FRIGATE_MQTT_USERNAME: "{{ .MOSQUITTO_USERNAME }}"
        FRIGATE_MQTT_PASSWORD: "{{ .MOSQUITTO_PASSWORD }}"
  dataFrom:
    - extract:
        key: reolink
    - extract:
        key: mosquitto
