---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: minio
spec:
  scheme: HTTPS
  staticConfigs:
    - targets: ["https://s3.robsonhome.cloud"]
  metricsPath: /minio/v2/metrics/cluster
