---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: minio
spec:
  scheme: HTTP
  bearer_token: ${SECRET_MINIO_BEARER_TOKEN}
  staticConfigs:
    - targets: ["10.1.30.200:9000"]
  metricsPath: /minio/v2/metrics/cluster
