---
- name: Create Scrypted data directory
  file:
    path: "{{ scrypted_data_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Deploy Scrypted container
  docker_container:
    name: "{{ scrypted_container_name }}"
    image: "{{ scrypted_docker_image }}"
    state: started
    restart_policy: "{{ scrypted_restart_policy }}"
    network_mode: "{{ scrypted_docker_network }}"
    privileged: "{{ scrypted_privileged }}"
    volumes:
      - "{{ scrypted_data_dir }}:/server/volume"
    env:
      SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION: "Bearer SET_THIS_TO_SOME_RANDOM_TEXT"
      SCRYPTED_WEBHOOK_UPDATE: "http://localhost:{{ scrypted_port }}/v1/update"
    labels:
      com.scrypted.service: "scrypted"
    pull: yes

- name: Wait for Scrypted to be ready
  wait_for:
    port: "{{ scrypted_port }}"
    delay: 5
    timeout: 60
