wireguard_gateway_private_key: ENC[AES256_GCM,data:ILhKv6xom56Xf3a6fLOWZkKL8DYPssETo61F/byUvR6JLuulIyFto8pcxT0=,iv:5aJ71rD4rYTLSDbPhKPnIwjHmWt1jwmM988du5/vyRE=,tag:FN9pQxyiJ26nbrlZ8msS5Q==,type:str]
#ENC[AES256_GCM,data:1hhuhpmGcjZRhEr/KlbHhnP4cQ==,iv:LMfn7ekGoD/svgOkxsFY3k0CLLuDmgjDHPq6luzCBQk=,tag:4Qmn4QxM4L8dorpVQRiT/g==,type:comment]
wireguard_gateway_public_key: ENC[AES256_GCM,data:GOS2HQElf24tAtYZF7Gbt9vxwoHIdFPWQsfJYWU9RgSo7FROWuzWYW8LIDE=,iv:FGukOpKyi34tkdanLeBZom+wHshXdHNdTa2u72dAEFU=,tag:ZB6EtsETSeNWa9HGXdbTew==,type:str]
#ENC[AES256_GCM,data:Wr1jmFNj30+jRZ5QNle8QRYMeg==,iv:IeVI0VYtTFa72SNJbLg15KoFK2u8NpiGMtVkxdHavTo=,tag:QSvgZZdGowC4twGV4/cOmg==,type:comment]
wireguard_client_private_key: ENC[AES256_GCM,data:8hBxPlFXDOSUyjK+8tV1Lu81YTHHfiNn+vYweond8K2wiJq2W1FEATFibu8=,iv:QDYtoJuNgVNTYyGIVN8fOyj88RiRkuCoCOSHzEwoTHg=,tag:H5SVozo6/x4Z/nTug79+LA==,type:str]
#ENC[AES256_GCM,data:dQYu5i+Qz/6Njq9BVMnQiG8V,iv:cV1MzsUx/1XT/LdPdvkGkVjWeQI2L454uKdVsGe+fWg=,tag:D7R5NgQhzr+WmWAdWOaKsw==,type:comment]
wireguard_client_public_key: ENC[AES256_GCM,data:iR9P5DvYOjNoPunzgS3ZB+BqTEDqhPh2a8XUaBZWfjCHYizhOkBUUypKGkw=,iv:Eka6TuZA7jY9Cgykv8o6Fwx8dPhffdSNafysZ2RUKcs=,tag:1uvO2oju4+gcucuD9YTtgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2rgupgcxr8d4mf9jf5rgm8cetz9utdvv9dzqk09y0f4c08zyvdsdw8h2v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eHQrNWJYNzQzeUYwQ3A0
            bUZJeXZKYVZSVERqV3FDcVc2dUlQMXJqU0RzCm1lcG1UMEFRdFdIS1ZiZDU0Vnk1
            MVJOUTRsYldxTlFvR2wvaDZlNjlWVlkKLS0tIHB0YStSczNPeUkwbnYwWGdVeHJS
            Y05RU1JXZEpTS0QwRVRtNVFLR1FrWjQKB8Py98ZjyafBNCNyy5WhhLup/LYh9ddx
            i9zReFNmgQ17s5GrThD8GkXplW0xxtamM3zowkD8nEvyJ6DkZ4+Ojg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-21T00:01:31Z"
    mac: ENC[AES256_GCM,data:jvgK4cxSTk0AX+hh9NkCWQiNHVtCtYsc2MF6maYKjgSzPI+GCi6IdLIhU4FhMkLBypdg7ODhgHLhxm560fLx5y6eZ89g9m3k3YuFYP9tHP2b8JJla2z/oG+A1l+Htdf5nCrvwyduEAU0BjNTGLlmE835RTLzEoopaWIPnPvVRi0=,iv:4jo8ZJcjMp8b8KKESlaYa6F+e8P9t2p5S4xKCEn4xNs=,tag:71VnxM3kicPcRgmh6yGIbQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
