---
all:
  vars:
    ansible_user: dylan
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  children:
    linode_vps:
      hosts:
        aiostreams-srv:
          ansible_host: aiostreams.robsonhome.cloud

    raspberries:
      hosts:
        pi-homeauto:
          ansible_host: 10.1.20.90
        pi-net01:
          ansible_host: 10.1.20.91
        pi-net02:
          ansible_host: 10.1.20.92
        pi-pi-media:
          ansible_host: 10.1.20.93
        
    # sffs:
    #   hosts:
    #     nuc:
    #       ansible_host: 10.1.20.80
          