---
- name: add ip4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: true

- name: add ip6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 1
    state: present
    reload: true

- name: enable forwarding
  command: systctl -p /etc/sysctl.conf

- name: Add Tailscale package signing key and repository
  command: curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/lunar.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null && curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/lunar.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list

- name: Update apt
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install Tailscale
  apt:
    name: tailscale
    state: present
# - name: Start tailscale
#   command: tailscale up --accept-routes
