---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ring-mqtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ring-mqtt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        MQTTUSER: mqtt_user
        MQTTPASSWORD: "{{ .mosquitto_password }}"
        DISARMCODE: "{{ .RING_DISARM_CODE }}"
  dataFrom:
    - extract:
        key: mosquitto
    - extract:
        key: ring
