---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app ring-mqtt
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: mosquitto
      namespace: default
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      ring-mqtt:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/tsightler/ring-mqtt
              tag: 5.6.3
            env:
              MQTTHOST: "mosquitto.default.svc.cluster.local"
              ENABLECAMERAS: "true"
              SNAPSHOTMODE: "true"
              ENABLEPANIC: "true"
              MQTTHASSTOPIC: hass/status
              MQTTPORT: 1883
              DEBUG: "ring-mqtt"
            envFrom:
              - secretRef:
                  name: ring-mqtt-secret
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
            securityContext:
              privileged: true

    service:
      app:
        controller: ring-mqtt
        ports:
          http:
            port: 8554

    persistence:
      config:
        enabled: true
        existingClaim: *app
        advancedMounts:
          ring-mqtt:
            app:
              - path: /data
      config-file:
        type: configMap
        name: ring-mqtt-configmap
        advancedMounts:
          ring-mqtt:
            app:
              - path: /data/config.json
                subPath: config.json
      ring-state:
        type: configMap
        name: ring-mqtt-configmap
        advancedMounts:
          ring-mqtt:
            app:
              - path: /data/ring-state.json
                subPath: ring-state.json
