---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app ring-mqtt
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: mosquitto
      namespace: default
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image: tsightler/ring-mqtt
            tag: v5.6.3
          envFrom:
            - secretRef:
                name: ring-mqtt-secret
          resources:
            requests:
              cpu: 10m
            limits:
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      service:
        main:
          ports:
            http:
              port: 8554
      persistence:
        data:
          existingClaim: *app
          globalMounts:
            - path: /data
        config:
          type: configMap
          name: ring-mqtt-configmap
          globalMounts:
            - path: /data/config.json
              subPath: config.json
