# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: ring-mqtt-config-secret
stringData:
    config.json: ENC[AES256_GCM,data:OBUsYdXyAG1xxsrH/KAnAxF5Irc2Jrt2XIxQhL1AsOPA2p8pk+n+einv2DCR89GqhC47dPv6v5KPhYzaLe/JfOa7OhQ7/mJSL28v1bNjUiLpujS+wOhfFxCqpCILnVSgsnEJh35efb+yd9QYBVsvKOmLyGFLkPq98MAXR3Qw6QWnCqebmxiGOe/osFxUajMf+uOLkoZmAtqIwMpm08y2xmMqk9QlPSQaKrEZl64e3iDK4nHDKlVt/n0G2yTONpPYA30vz5o2M7MErr63+RTcqoAhGRY7Lit5NDkgOCo9MD+4C0IWgFujgo5bQg101saJ+vDSnQFs+0cBSgLG3yOALy82pGKpNQtNCqrdg0eNGe4pRIRJPgLBZvqer3qofFY5vTNhMAqc2gYVl/hqu9DhcloDNu1pyfkH4W0EolEA4Ae+CVS/tZX4QMXIYGupYvmZMNFtvmi71rUyVdeBq5gbMbWDN/5jCMJ6,iv:aY2m4NEHaCjxMjIwWEpdKSxrGVYUmol0wEo6DlkJcUA=,tag:xggZTHjRfeJM0fk3oqdW4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2rgupgcxr8d4mf9jf5rgm8cetz9utdvv9dzqk09y0f4c08zyvdsdw8h2v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZXJ6U1ZSYUZrc0E4Tk5m
            Yitnck05R3cvWjJDaFVicjE4d3RjWkRyU0FJCkUweGxsc2V1ZXloaVJTTndDNVhz
            U1hPdkVMZzJuVzRYbXcvbzRmeStUSUkKLS0tIHgvNjhSa3NRMy9YdENpY1l2RFlP
            Uk5HOVlzVm1XYmFTSVlXdzZDS0h0dzAKa8GrP036uumlgseYinchZkCLfzNVfiat
            Mkhhcl9H60vrNz+7LRRuRMLybDSRsHpTeHLzOo3N8KucOuIqPLJqFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-16T00:16:02Z"
    mac: ENC[AES256_GCM,data:lA2zYSgbwTbQGJg8eH/+CIwQD8QRxkHi3CUHUZtyHg8+gSguNqfrFRujvlIKPnumy2uHGOzwK675p7acjaI+/pQekU8TpTnRz7TG8RI7+Zb5W96MdOOnRgeffSYlIRnDShkWQ/smdMIvIUaBmpshcVGJJoxA4ufhHIAXP1Foz0A=,iv:auB63n2J4yucRPYcshDjlQY7PJzst+eFcsJWvKhXli4=,tag:5hvIyhQxbQUvpIYGVIJ4+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
