# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: ring-mqtt-config-secret
stringData:
    config.json: ENC[AES256_GCM,data:AG0BKLWd1AYp9TApbQRooIR4oUbW07wS6EV+yAE7IxEqHs/cnhMCNkdpstColHcB2q/YaraZB6EF/+XjL4jT0I4n1khok7c5EKLkRJb9GkIMqAFALiK03AObH7VUJ808Ea82FRRegxphDnu8dF+lSY9xugaR5t8W4rdRtMWoY789VZ0psVBwEtKO5FJOvba6BLRGH8F6TKUyxpqxb5ZweZUwUe7AeLOX84BFbhf3uUi8/sDB+FMy4XRbc6wW6euCdX2NYu4vT79JNpDiV4KuT8LRMYr9lJdzBwOaOLALuGdsJ8u4f0AaHQAS+z69pECMNQpdAx9IEzHiSYFjLzkLtczxgG8kmKnKU4V0lB4GgM7i3tjiRupRYhSWQzg2yYlZ/q/S/u1k6x5Lmq+j6nQkfbFZpOwBkfKJrBTfAdAN57SQjoZLbqNyUC5koSEolSs/dAmIG/LIm8ZEMGovvMKBVA==,iv:OGHYH5j2jlJEBD1bEMjhP2Tj90s0vgWZ+vD/E+jLf1g=,tag:BAIf5/voovOYYLvqzfdl4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2rgupgcxr8d4mf9jf5rgm8cetz9utdvv9dzqk09y0f4c08zyvdsdw8h2v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRWE3cWNoMmliMjJKZ3lH
            cVp4WVgrVVk5ZnVIS3FZbnQwTjhGU0s1am13Ckx1aGpKQkxlZFNhODM2OGRFRk85
            dVRpU0VaMkNVT1lmeVMrNHJpZFhpWG8KLS0tIER6R3ZWYVMxS3p3dGFJSmM2d0cv
            bnh4TWN0bzNJR0tIU05rbjZEU1g5WlEKK9WuwQrTpZ7mR+/cPre33v54BsTaA7xE
            Ypw9agssV3n9G+VJ0Pd4xYYzWHWENSXVqWkTL0ylVQGbcJUcIbDzkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-29T04:29:16Z"
    mac: ENC[AES256_GCM,data:H7RNRWUtbfDq9LLrfeSvzCHkBh8HkgKhKTlF3jQprMkAX7NJIw3PxZudGe1guzhA3ycNVnufGPnYGdP09dYhNOb8Yg/U3yisprIo++ubuVK8HAmnzE2aL3tqM+q49J/LdGjtW0+WNyn9sMBquAuh6yrJ5dOZ4LXsWIVBGsKIm3Q=,iv:S5GCHrOV0hvW0PB6B3cmJqyAteboCmwa06MYNjD2hX0=,tag:ppwynikZ1KCRAVrhJsVbdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
