---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    autoDirectNodeRoutes: true
    bgpControlPlane:
      enabled: true
    bandwidthManager:
      enabled: true
      bbr: true
    bpf:
      masquerade: true
    bgp:
      enabled: true
    cluster:
      name: kubernetes
      id: 1
    containerRuntime:
      integration: containerd
      socketPath: /var/run/k3s/containerd/containerd.sock
    devices: eno1
    enableRuntimeDeviceDetection: true
    endpointRoutes:
      enabled: true
    enableCiliumEndpointSlice: true
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
          annotations:
            grafana_folder: Cilium
      relay:
        enabled: true
        rollOutPods: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          className: internal
          hosts:
            - &host hubble.robsonhome.cloud
          tls:
            - hosts:
                - *host
    ipam:
      mode: kubernetes
    ipv4NativeRoutingCIDR: 10.42.0.0/16
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6444
    kubeProxyReplacement: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    loadBalancer:
      algorithm: maglev
      mode: dsr
      l7:
        backend: envoy
    envoy:
      enabled: true
    ingressController:
      enabled: false
    gatewayAPI:
      enabled: true
    localRedirectPolicy: true
    operator:
      rollOutPods: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: true
        annotations:
          grafana_folder: Cilium
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    dashboards:
      enabled: true
      annotations:
        grafana_folder: Cilium
    rollOutCiliumPods: true
    routingMode: native
    securityContext:
      privileged: true
      capabilities:
        ciliumAgent:
          - PERFMON
          - BPF
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUI
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
