include "/etc/bind/named.conf.key";

controls {
    inet 127.0.0.1 port 953
    allow { 127.0.0.1; } keys { "tsig-key"; };
};

acl docker {
  172.17.0.0/16;
  172.18.0.0/16;
  172.19.0.0/16;
  172.20.0.0/16;
  172.21.0.0/16;
  172.22.0.0/16;
  172.23.0.0/16;
  172.24.0.0/16;
};


acl trusted {
 10.1.1.0/24;
 10.1.10.0/24;
 10.1.20.0/24;
 10.1.30.0/24;
 10.1.33.0/24;
 10.1.40.0/24;
 10.1.100.20/32;
 10.1.100.21/32;
};

options {
 forwarders {
   10.1.1.1;
 }
 allow-transfer { none; };
 allow-query { 127.0.0.1; docker; trusted; };

};

zone "robsonhome.cloud" IN {
  type master;
  file "/etc/bind/robsonhome.cloud.zone";
  update-policy { grant tsig-key zonesub any; };
};
