---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: plex
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: intel-device-plugin-gpu
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      plex:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values: ["frigate"]
                  topologyKey: "kubernetes.io/hostname"
          enableServiceLinks: false
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109
              - 10000

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.40.1.8227-c0dd5a73e@sha256:a60bc6352543b4453b117a8f2b89549e458f3ed8960206d2f3501756b6beb519
            env:
              TZ: America/New_York
              PLEX_ADVERTISE_URL: http://10.45.0.20:32400,https://plex.robsonhome.cloud:443
              PLEX_NO_AUTH_NETWORKS: 10.42.0.0/16
            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
              limits:
                gpu.intel.com/i915: 1
                memory: 8Gi

    service:
      app:
        controller: plex
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: 10.45.0.20
        ports:
          http:
            port: 32400

    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.robsonhome.cloud
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        hosts:
          - host: &host plex.robsonhome.cloud
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        existingClaim: plex
        advancedMounts:
          plex:
            app:
              - path: /config

      plex-cache:
        existingClaim: plex-cache
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Cache

      logs:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /logs

      transcode:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /transcode

      media:
        type: nfs
        server: 10.1.10.210
        path: /mnt/tank/media
        advancedMounts:
          plex:
            app:
              - path: /media
