---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app plex
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: intel-device-plugin-gpu
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      plex:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values: ["frigate"]
                  topologyKey: "kubernetes.io/hostname"
          enableServiceLinks: false
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            runAsNonRoot: true
            supplementalGroups:
              - 44
              - 105
              - 109

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/plex-beta
              tag: 1.40.2.8383-15541a816
            env:
              TZ: "America/New_York"
              ADVERTISE_IP: "https://10.45.0.22:32400,https://plex.robsonhome.cloud:443"
              PLEX_NO_AUTH_NETWORKS: 10.42.0.0/16
              # ALLOWED_NETWORKS: "10.1.0.0/16"
              # HOSTNAME: "plex"
            resources:
              requests:
                cpu: 100m
                memory: 3Gi
                gpu.intel.com/i915: 1
              limits:
                gpu.intel.com/i915: 1
                memory: 6Gi

    service:
      app:
        controller: plex
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: 10.45.0.22
        ports:
          http:
            port: 32400

    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.robsonhome.cloud
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        hosts:
          - host: &host "plex.robsonhome.cloud"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]

    persistence:
      config:
        existingClaim: plex
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server

      plex-cache:
        existingClaim: plex-cache
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Cache

      logs:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /logs

      transcode:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /transcode

      tmp:
        type: emptyDir

      media:
        type: nfs
        server: 10.1.10.210
        path: /mnt/tank/nfs/media
        advancedMounts:
          plex:
            app:
              - path: /media
