# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: xteve-m3u-secret
stringData:
  iptv.m3u: ENC[AES256_GCM,data:O1b5k56/GxSVbrM+xomjAOsARfxIbkWdtAHQUN6nKoVY/42zOOtZvZ5xFy3EACmot/QVFKJE0ajzgdO6TcEMtyhSwug6vS23dObqjm/hqxwOXEM6ATfKYDGHmNrpLU8CidItqzHBXrLufzn4SyQYcMTWhrvf/NB+cLN6F/zsFy8GuuZzvs5vNStTh9zoKK/kdDu3YnqE7beoeKT9tSm4RJnx2cw7aeBW1m+loqiT+9xMC3GWHyyQsWrtITYe0H+MLZqsOCrNEhuSZN3OvIXDvw7mfsX3eZw0K6clpGoE3oug3SQjc/rmq8sXSAb3u79MlUefyP98lwyI4Ke4maRZZu+fVPpYaMpzQQSufl3XljfumXOUD6N++Rm47nVwbsKHjJduKOuVoTjP6KzVKypgnSGXa/wqZbyHlqX9dHa512BmVMuAzsNoRiUkfkTKtbHxZqlb9q68CMmHB7eGH9u9mOh9kL7VMCaIuEkZE+/neAIbeNQNK8IdiCOXliRiRnD/pOKLaX988u2mKaMISVe3C4UeAoYl8KhzXnsSDbxLOpuVBGNhzGpCzH7HoGuOjRrEQv7oVBhcC4fsaEKfGW6gzpQ/tpOukqhZ6wBUp4WNhnjaKUsIzJFG0HaLF9Qj7b3UGxrxkezaPl2hjvEvmNccYPalyjFoZ94FFYJvUJstJrw5eszUFB5/+5Drwx1qtKuGdkCgNrsVxXnIXdmVRPOMysgk1JXNZlEXPGtH/MgHZ6ZmX1qM5s3LJeh7bBJtze4OjdsT79B2eq+if4m26hXcuGWJ9lTiVPlj+z4=,iv:JKnWpqd9GJtd6Z8HjPIoxaKIVmLJ3dC3tLmm6HCB73Y=,tag:JtqaWdROPC88jNDy8d6pyg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1g2rgupgcxr8d4mf9jf5rgm8cetz9utdvv9dzqk09y0f4c08zyvdsdw8h2v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaHYyYUxqTExTdGM4T1Rh
        b2tTWWYyYUNrYVM0LzVuNm5KcVlGZnU4WFY0ClhleEpxdE1qWUk2TUQzMHV4Vlo4
        RWRwOVV1allqeHlvS0FmYzAyVFdoOGMKLS0tIEs1MjZXU0Q5UDdWWFllYWdYVnlo
        bkJ4eFNqc1FyWndmUTF5RnpDTHhYTmcKQcGPNGDtPbacak8OOCr4Mvn6dLI3Z/i6
        GcWnAtAjFbiYF0Txm124qTPfZOu2vz0E/QiA4Ffq+Wf8uboSRaBzVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-03-31T14:01:48Z"
  mac: ENC[AES256_GCM,data:uO/DIhc1wNgror4SfGR9z9qF9BZ32Ih6xsa0k+AVCtINzvJ2GPuRddotw7VrKwxUEXru4ol/Jk7t7GyBjHn2FH7SWN9S4lszrRBxLPUXE/K8v55s4iFTcna7RbFTpnrb1eXLwjdPvDUNXbzvGnxszuohryIGVpIxIItQJqVOZv4=,iv:A/CKDhDs8Hwm+C35MHUEx/jPjO3U8wAyK3DUnJpZHyg=,tag:cbp7ZAkLBRDezk3wpGA6tA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
