---
version: "3"
services:
  headscale:
    image: headscale/headscale:0.22.3
    container_name: headscale
    #2.0-alpha1
    hostname: headscale
    volumes:
      #create config.yaml first
      - ./config:/etc/headscale/
      - ./data_headscale:/var/lib/headscale
    # ports:
    #   - 8080:8080
    entrypoint: headscale serve
    restart: unless-stopped
    networks:
      reverseproxy-nw:

  headscale-ui:
    container_name: headscale-ui
    hostname: headscale-ui
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    networks:
      reverseproxy-nw:
    # ports:
    #   - 9443:443
networks:
  reverseproxy-nw:
    external: true
