---
- hosts: kubernetes
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Prepare new System
      notify: Reboot
      block:

        - name: Configure Root Password
          become: true
          user:
            name: root
            update_password: always
            password: "{{ vault_root_password | password_hash('sha512') }}"

        - name: Configure Root Password
          become: true
          user:
            name: dylan
            update_password: always
            password: "{{ vault_default_password | password_hash('sha512') }}"

        - name: Grant main sudo access
          lineinfile:
            path: /etc/sudoers
            line: "{{ me.user }} ALL=(ALL) NOPASSWD: ALL"
            validate: 'visudo -cf %s'
          become: true

        - name: User Configuration | SSH keys
          authorized_key:
            user: "{{ me.user }}"
            key: "https://github.com/DylansDecoded.keys"
            state: present


  handlers:
    - name: Reboot
      reboot:
        msg: Rebooting nodes
        reboot_timeout: 3600
