---
- hosts: kubernetes
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: remove /etc/resolv.conf
      command: rm /etc/resolv.conf
      become: true

    - name: Copy new /etc/resolv.conf
      copy:
        src: files/resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644
      become: true

    - name: make the resolv.conf immutable
      command: chattr +i /etc/resolv.conf
      become: true




    # - name: Install resolvconf
    #   apt:
    #     pkg: resolvconf
    #     state: present
    #     install_recommends: false

    # - name: enable resolvconf
    #   service: resolvconf
    #   state: enabled
    #   become: true

    # - name: Start resolvconf
    #   service: resolvconf
    #   state: started
    #   become: true

    # - name: Stop dhclient from editing /etc/resolv.conf
    #   command: echo 'make_resolv_conf() { :; }' > /etc/dhcp/dhclient-enter-hooks.d/leave_my_resolv_conf_alone
    #   become: true


    # - name: Set interfaces file
    #   template:
    #     src: templates/interfaces.j2
    #     dest: /etc/network/interfaces
    #     owner: root
    #     group: root
    #     mode: 0644
    #   become: true



        # - name: Configure Root Password
        #   become: true
        #   user:
        #     name: root
        #     update_password: always
        #     password: "{{ vault_root_password | password_hash('sha512') }}"

        # - name: Configure Root Password
        #   become: true
        #   user:
        #     name: dylan
        #     update_password: always
        #     password: "{{ vault_default_password | password_hash('sha512') }}"

        # - name: Grant main sudo access
        #   lineinfile:
        #     path: /etc/sudoers
        #     line: "{{ me.user }} ALL=(ALL) NOPASSWD: ALL"
        #     validate: 'visudo -cf %s'
        #   become: true

        # - name: User Configuration | SSH keys
        #   authorized_key:
        #     user: "{{ me.user }}"
        #     key: "https://github.com/DylansDecoded.keys"
        #     state: present


  handlers:
    - name: Reboot
      reboot:
        msg: Rebooting nodes
        reboot_timeout: 3600
