---
# - hosts: all
#   gather_facts: true
#   become: true
#   roles:
#     - base

- hosts: docker
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: geerlingguy.docker
      become: true
      vars:
        docker_install_compose_plugin: "{{ ansible_os_family == 'Debian' }}"
        docker_users:
          - "{{ me.user }}"
    - docker-cleanup
    - nfs
    - netbootxyz





# - hosts: docker-hosts
#   gather_facts: true
#   become: true
#   roles:
#     - role: geerlingguy.docker
#       become: true
#       vars:
#         docker_install_compose_plugin: "{{ ansible_os_family == 'Debian' }}"
#         docker_users:
#           - "{{ me.user }}"
#     - docker
#     - frigate

# - hosts: wireguard
#   gather_facts: true
#   become: true
#   roles:
#     - wireguard
