- hosts: pi4-nodes
  gather_facts: true
  become: true
  roles:
    - base
    - role: geerlingguy.docker
      become: true
      vars:
        docker_install_compose_plugin: "{{ ansible_os_family == 'Debian' }}"
        docker_users:
          - "{{ me.user }}"
    - role: docker-cleanup

