---
- hosts: vps_servers
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
    # - role: base
    # - role: tailscale
    - role: geerlingguy.docker
      vars:
        docker_install_compose_plugin: "{{ ansible_os_family == 'Debian' }}"
        docker_users:
          - "{{ me.user }}"
    - role: nginx-proxy-manager



