---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cross-seed-secret
    template:
      engineVersion: v2
      data:
        config.js: |
          module.exports = {
            delay: 20,
            qbittorrentUrl: "http://qbittorrent.default.svc.cluster.local:8080",
            torznab: [
              `http://prowlarr.default.svc.cluster.local:9696/3/api?apikey=$${process.env.PROWLARR_API_KEY}`, // mam
              `http://prowlarr.default.svc.cluster.local:9696/5/api?apikey=$${process.env.PROWLARR_API_KEY}`, // hds
              `http://prowlarr.default.svc.cluster.local:9696/9/api?apikey=$${process.env.PROWLARR_API_KEY}`, // ipt
              `http://prowlarr.default.svc.cluster.local:9696/11/api?apikey=$${process.env.PROWLARR_API_KEY}`, // dc
              `http://prowlarr.default.svc.cluster.local:9696/14/api?apikey=$${process.env.PROWLARR_API_KEY}`, // thhq
              `http://prowlarr.default.svc.cluster.local:9696/16/api?apikey=$${process.env.PROWLARR_API_KEY}`, // tos
              `http://prowlarr.default.svc.cluster.local:9696/17/api?apikey=$${process.env.PROWLARR_API_KEY}`, // mlk
              `http://prowlarr.default.svc.cluster.local:9696/53/api?apikey=$${process.env.PROWLARR_API_KEY}`, // fnp
              `http://prowlarr.default.svc.cluster.local:9696/86/api?apikey=$${process.env.PROWLARR_API_KEY}`, // uplcx
            ],
            port: 80,
            apiAuth: false,
            action: "inject",
            includeEpisodes: false,
            includeSingleEpisodes: true,
            includeNonVideos: true,
            duplicateCategories: true,
            matchMode: "safe",
            skipRecheck: true,
            outputDir: "/config",
            torrentDir: "/qbittorrent/qBittorrent/BT_backup",
          }
  dataFrom:
    - extract:
        key: cross-seed