---
- name: Configure IOMMU
  hosts: all
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5

  tasks:
    - name: Enable IOMMU for hosts (grub)
      become: true
      replace:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        replace: "{{ iommu_config }}"
        backup: yes
      when: bootmgr == 'grub'

    - name: Update grub
      become: true
      shell: update-grub
      when: bootmgr == 'grub'

    - name: Configure (modules)
      template:
        src: files/modules
        dest: /etc/modules
        owner: root
        group: root
        mode: 0644

    - name: Reboot and apply
      reboot:
        reboot_timeout: 300
        msg: "Rebooting to apply IOMMU changes"
        connect_timeout: 5
        pre_reboot_delay: 0
        post_reboot_delay: 30

    - name: Verify iommu is enabled
      shell: dmesg | grep -e DMAR -e IOMMU
      register: iommu_enabled
      changed_when: false
      failed_when: false


