---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app jellyfin
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: intel-device-plugin-gpu
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values: ["frigate"]
                  topologyKey: "kubernetes.io/hostname"
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [44, 10000, 109, 65537]
        # initContainers:
        #   init-permission:
        #     image:
        #       repository: ghcr.io/cbc02009/busybox
        #       tag: 1.36.1
        #       pullPolicy: IfNotPresent
        #     command:
        #       - sh
        #       - -c
        #       - chown -R 568:568 /media
        #       - chown -R 568:568 /config/transcodes
        #     securityContext:
        #       runAsUser: 0
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/jellyfin
              tag: 2021.12.16
            env:
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_FFmpeg__probesize: 50000000
              JELLYFIN_FFmpeg__analyzeduration: 50000000
              JELLYFIN_PublishedServerUrl: &loadBalancerIP 10.45.0.57
              TZ: America/New_York
            probes:
              liveness: &probes
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 200m
                memory: 1Gi
              limits:
                gpu.intel.com/i915: 1
                memory: 3Gi
    service:
      app:
        controller: jellyfin
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: *loadBalancerIP
        ports:
          http:
            port: 8096
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.robsonhome.cloud"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: &host jellyfin.robsonhome.cloud
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]

    persistence:
      config:
        existingClaim: *app
        advancedMounts:
          jellyfin:
            app:
              - path: /config

      # jellyfin-cache:
      #   existingClaim: jellyfin-cache
      #   globalMounts:
      #     - path: /cache

      media:
        type: nfs
        server: truenas.robsonhome.cloud
        path: /mnt/tank/nfs/media
        advancedMounts:
          jellyfin:
            app:
              - path: /media


      tmp:
        type: emptyDir

      transcode:
        type: emptyDir
        globalMounts:
          - path: /config/transcode