apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:z/azwsyTSpSNN+pB4Hnv+w==,iv:cQQBouMjQ/7XKLwenoid1LF19cPOLi7iPdxfwxzX2KU=,tag:wKbcQ6D7ZrXeWYc4DDiJCg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:D1KdjWSDIdb1SX+NkBI7J+v+3JJweQ==,iv:A+E/E4qLDpVDr7aChj2PVRtAttJMV7ozwBTil+Erxas=,tag:37ZLKdE/wYu6ZRAwLmCUdA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:IU8pRQwVaCHlBXl9CbBLL5lPfm54TlofimcPRtNVeBgBILij,iv:zWl0FvPANGTDxES4DPKnMzRqhNuC9JM2snEAvXQgRAk=,tag:8+6VegX2FE/pfnZUgHclvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j0ka43yg0mqflhf9wnnj8n5vq3f8awq3sz3h9zxjvfrrt55urdesufzzu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTHBOSEx0RnBHV3VkRlRm
            aWMyQVlBMThaaUU2Q01EYXNJc2xPcFFPU0FvCjlNYXMzVnVsVCsvUmxQS2V2dTZB
            ektuWkxJVEc5MXVtOVZpc3BLbU5RejQKLS0tIGdBRmZaVE4xaEYrVlZuQStkUnZB
            UzdRczh4V1lpb0cvYXNpbTF6bWpLSnMKokoZCqJrmQ/Je/kHTBsjV2NaAgbCaI2i
            4fLOMxrss8uqsHzpnC+CnMGfzjAdASltdNl2wXHGiNY6EbFxbTc2Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-10T02:52:57Z"
    mac: ENC[AES256_GCM,data:x+eJNEueLvHf6j2pS5mZden3NnSRwyMFaNk0gUA6aiodlRqdHNeJ2K0soZVrdD3zF2WEpTdJYJARiQXIZ0778SUOmjv/67RyNzOb63+R4C0c/eomg/M90Uf8VPcWXa2fKe8aQvkN6QMtXLllDj7yfXhRybj0OCgJ6xlrrdMi0uY=,iv:yBdvQtr0U3siLerQ5BiSEv7tNPWyC/il/8lvUiWdzt4=,tag:/6LndHoDaQ8MnOTUTUbjEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
