apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ddB9jfJolcTa+LTbhPznyA==,iv:Z9tTuBOiht4jjxXhUjtiv4mhSU9COXwocFh+0eD/E90=,tag:1TkS51e/Yu75vbrEberkMw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:HyMK76BhDDA6TAUM7y9L7yc7sVRAQQ==,iv:nYtyF90Qjf2FtD+6nbH4s3bamJ6BCKyFkO6JWteOwKA=,tag:Bq5RNbTqRVzzaW08YAC0Lg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:pTzYeFJhjjx+RYXFFOPL6IKFeyNxcxKD7tye4BxgINPsFy5g,iv:SWr3zCsHNBa7PkMDUh9adOTdwk71UsHcm8VkbN827XU=,tag:vp7VM4CtD5Z3JFEEazqJeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2rgupgcxr8d4mf9jf5rgm8cetz9utdvv9dzqk09y0f4c08zyvdsdw8h2v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYzFHYzA5QWN3ZWwydUJr
            cUdkemtyMWYrSG1MalZZcnR2b2t6Q2t5NWhrCkQ2c25CYjRnUGRDSm5YQjY1c2po
            alYvdXdrajVNYm5SaDVZTEF2NFdNdGMKLS0tIHJiTnpneXFscFBuSFRRR1RNVGhu
            S21reTFKTk5Gb0pYYkc2eG5MU2VaejgKzENpRwyYNN0KUO9XoyzyDjCra0NU7+80
            fsavswAGI1QfTkSA74KL2b/V6MLdxgY2DSoc5oU99AJmTsEnLnGCsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-10T03:09:22Z"
    mac: ENC[AES256_GCM,data:BpWkZl9o9faHW2fL5WXHsjEKAaB//wKY50yqMI+afXppmqR3g4xUFA0UIiuT7H0362cH2f4g278OkBavOibkojk631AaZd4yxixgYR+sUeNg5w5+kKn8y0ZLKqPM//E8+FxvzJzYUatBTTKWwGx+Z28RSKRulo4xxanMYS/mspo=,iv:R41vPuS8/7jlPf7EDzonCS4FttBDwpJArQboks2Elco=,tag:dlv5EHBVZfaeUPfPCGcXBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
