apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  CLUSTER_SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:QdGN3+TFD+xSiXG1qsi3qFT0EEU7KhWPRK06gY2pzhA=,iv:Q/QzXm3kW6qyQqba8LncUcf/2HE4ACXNEF5imBoiO3Q=,tag:v2RpW5UPYtQKQkW4ZdWCdQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1g2rgupgcxr8d4mf9jf5rgm8cetz9utdvv9dzqk09y0f4c08zyvdsdw8h2v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiY2s4elJsbWJPTG4waVZm
        VzN6alhPVjhYeDJ4WWNjK05tQ0J6MUVpcGxrCllYcUhyTzJWVm1VQlZFNkl5QXRY
        L3AzOXdqaFByYnpodHlFckpUaDVFTWcKLS0tIFlpcXRTT2RjYlBYOVdHaGhVczdx
        S0Zxbmt1MGtjVVkvS2xyd3V4WE5JMUEKMTURvyQC3JPj2J/6GStBi58bRDZnLKVH
        hmrvAd8NLjKtOO+Wil2eMAHP/9naiG7R7sneWsZ/Bp/Z/ZZRSxlbpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-04-10T04:35:32Z"
  mac: ENC[AES256_GCM,data:8ZgsjfNjyLWqo4H2nOBMFJeRQbcWxfQDOhf+9u4+gkRxpWDWacMEnG1rbt+SmIGsNN8s/iEBSEOVXSbTrD3E2eVy52z8zP1D6iE8SDQtCBx0Adil+fRdOSAEuvG2MrQNXmmfrLJFrQp+Cb1rOACmCJbFZGNPJVEDmPBh6Sx2VMM=,iv:775qB2QRYZXrn+4swpCxMzKnf5h/XQmAjmojRMklXyM=,tag:0Gubh23g8LuOC8IYSSYxBw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
