---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 4.6.3@sha256:79ac03232dcb3e172fe028f66784f88ed8c49bd5c05ef4a443d675681b37d6ec
            env:
              TZ: America/New_York
              UMASK: "022"
              QBITTORRENT__PORT: &port 8080
              # QBITTORRENT__BT_PORT: &bittorrentPort 58462
              QBITTORRENT__WebUI__AlternativeUIEnabled: false
              QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelist: >-
                10.1.1.0/24,
                10.1.10.0/24,
                10.1.20.0/24,
                10.1.33.0/24,
                10.1.40.0/24
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 200m
              limits:
                memory: 4Gi

          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.37.0
            env:
              VPN_SERVICE_PROVIDER: custom
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              VPN_ENDPOINT_PORT: 51820
              VPN_PORT_FORWARDING: on
              VPN_PORT_FORWARDING_PROVIDER: protonvpn
              FIREWALL_INPUT_PORTS: 8080
              FIREWALL_OUTBOUND_SUBNETS: 10.42.0.0/16,10.43.0.0/16
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
              allowPrivilegeEscalation: false

          port-forward:
            image:
              repository: ghcr.io/bjw-s/gluetun-qb-port-sync
              tag: v0.0.1
            env:
              GLUETUN_CONTROL_SERVER_HOST: localhost
              GLUETUN_CONTROL_SERVER_PORT: 8000
              QBITTORRENT_HOST: localhost
              QBITTORRENT_WEBUI_PORT: *port
              CRON_ENABLED: true
              CRON_SCHEDULE: "*/5 * * * *"
              LOG_TIMESTAMP: false
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65539
    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "qbittorrent.robsonhome.cloud"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent
        advancedMounts:
          main:
            main:
              - path: /config

      completed-script:
        type: configMap
        name: qbittorrent-scripts
        defaultMode: 0775
        advancedMounts:
          main:
            main:
              - path: /scripts/completed.sh
                subPath: completed.sh
                readOnly: true

      media:
        type: nfs
        server: 10.1.30.210
        path: /mnt/tank/nfs/media
        advancedMounts:
          main:
            main:
              - path: /data/media
