---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 4.6.3@sha256:a4ad890e8c4a287c17d12ca22eb1d84a046aba2efbd882bf7d6eb12459f6a70c
            env:
              TZ: America/New_York
              QBITTORRENT__PORT: &port 8080
              # QBITTORRENT__BT_PORT: &bittorrentPort 58462
              QBITTORRENT__WebUI__AlternativeUIEnabled: false
              QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelist: >-
                10.1.1.0/24,
                10.1.10.0/24,
                10.1.20.0/24,
                10.1.33.0/24,
                10.1.40.0/24
            securityContext:
              runAsUser: 568
              runAsGroup: 568
            resources:
              requests:
                cpu: 200m
              limits:
                memory: 4Gi
          gluetun:
            dependsOn: main
            image:
              repository: docker.io/qmcgaw/gluetun
              tag: v3.37.0
            env:
              VPN_SERVICE_PROVIDER: custom
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              VPN_PORT_FORWARDING: "on"
              DOT: "off"
              FIREWALL_OUTBOUND_SUBNETS: "10.42.0.0/16,10.43.0.0/16"
            envFrom:
              - secretRef:
                  name: gluetun-secret
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
          port-forward:
            dependsOn: gluetun
            image:
              repository: docker.io/snoringdragon/gluetun-qbittorrent-port-manager
              tag: "1.0"
            env:
              - name: QBITTORRENT_SERVER
                value: localhost
              - name: QBITTORRENT_PORT
                value: "8080"
              - name: PORT_FORWARDED
                value: "/tmp/gluetun/forwarded_port"
        # pod:
        #   securityContext:
        #     fsGroup: 568
        #     fsGroupChangePolicy: "OnRootMismatch"
        #     supplementalGroups:
        #       - 65539
    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "qbittorrent.robsonhome.cloud"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent
        advancedMounts:
          main:
            main:
              - path: /config

      gluetun-data:
        type: emptyDir
        advancedMounts:
          main:
            gluetun:
              - path: /tmp/gluetun
            port-forward:
              - path: /tmp/gluetun
                readOnly: true

      completed-script:
        type: configMap
        name: qbittorrent-scripts
        defaultMode: 0775
        globalMounts:
          - path: /scripts/completed.sh
            subPath: completed.sh
            readOnly: true

      media:
        type: nfs
        server: 10.1.30.210
        path: /mnt/tank/nfs/media
        globalMounts:
          - path: /media
