apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Communitcate:
        - Discord:
            - icon: discord.png # https://github.com/walkxcode/dashboard-icons
              href: 'https://discord.com/app'
    - Media:
        - YouTube:
            - icon: youtube.png
              href: 'https://youtube.com/feed/subscriptions'
    - Reading:
        - Reddit:
            - icon: reddit.png
              href: 'https://reddit.com'
        - Wealth Management:
            - icon: mdi-currency-usd
              href: 'https://www.bogleheads.org/wiki/Main_Page'
    - Dev:
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: 'https://kubesearch.dev/'
        - Github:
            - icon: github.png
              href: 'https://github.com/DylansDecoded/homelab'

  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Network:
        - Cloudflared:
            href: https://dash.cloudflare.com/
            icon: cloudflare-zero-trust.png
            description: Cloudflared Tunnel
            widget:
              type: cloudflared
              accountid: {{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}
              tunnelid: {{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}
              key: {{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}

        - Pfsense:
            href: https://pfs.robsonhome.cloud
            icon: pfsense.png
            description: Pfsense Firewall
            widget:
              type: pfsense
              url: https://pfs.robsonhome.cloud
              username: {{HOMEPAGE_VAR_PFSENSE_USERNAME}}
              password: {{HOMEPAGE_VAR_PFSENSE_PASSWORD}}

        - PiHole:
            href: http://pihole.robsonhome.cloud/admin
            icon: pihole.png
            description: PiHole DNS
            widget:
              type: pihole
              url: http://10.1.100.53
              key: {{HOMEPAGE_VAR_PIHOLE_API_KEY}}

        - Omada:
            href: https://omada.robsonhome.cloud
            icon: omada.png
            description: Omada Controller
            widget:
              type: omada
              url: https://omada.robsonhome.cloud
              username: {{HOMEPAGE_VAR_OMADA_USERNAME}}
              password: {{HOMEPAGE_VAR_OMADA_PASSWORD}}
              sitename: {{HOMEPAGE_VAR_OMADA_SITENAME}}

      - Home Automation:
          - Home Assistant:
              href: https://hass.robsonhome.cloud
              icon: home-assistant.png
              description: Home Assistant
              widget:
                type: homeassistant
                url: https://hass.robsonhome.cloud
                token: {{HOMEPAGE_VAR_HASS_TOKEN}}

  settings.yaml: |
    title: Dashboard
    theme: dark
    color: slate
    headerStyle: boxed
    providers:
      openweathermap: {{HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY}}
      home-assistant:
    hideVersion: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Network:
        style: row
        columns: 4
        icon: mdi-ethernet
      Home Automation:
        style: row
        columns: 2
        icon: mdi-home-analytics
      Media:
        style: row
        columns: 4
        icon: mdi-folder-play-outline
      Reading:
        style: row
        columns: 2
        icon: mdi-book-open-variant
      Dev:
        style: row
        columns: 2
        icon: mdi-code-braces

  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - search:
        provider: [google]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Welcome back!"
    - openweathermap:
        label: Waxhaw
        latitude: {{HOMEPAGE_VAR_OPENWEATHERMAP_LATITUDE}}
        longitude: {{HOMEPAGE_VAR_OPENWEATHERMAP_LONGITUDE}}
        units: imperial
        provider: openweathermap
        apiKey: {{HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY}}
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
