apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Communitcate:
        - Discord:
            - icon: discord.png # https://github.com/walkxcode/dashboard-icons
              href: 'https://discord.com/app'
    - Media:
        - YouTube:
            - icon: youtube.png
              href: 'https://youtube.com/feed/subscriptions'
    - Reading:
        - Reddit:
            - icon: reddit.png
              href: 'https://reddit.com'
    - Dev:
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: 'https://kubesearch.dev/'
        - Github:
            - icon: github.png
              href: 'https://github.com/DylansDecoded/homelab'
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Network:
        - Cloudflared:
            href: https://dash.cloudflare.com/
            icon: cloudflare-zero-trust.png
            description: Cloudflared Tunnel
            widget:
              type: cloudflared
              accountid: {{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}
              tunnelid: {{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}
              key: {{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}
        - Pfsense:
            href: https://pfsense.robsonhome.cloud
            icon: pfsense.png
            description: Pfsense Firewall
            widget:
              type: pfsense
              username: {{HOMEPAGE_VAR_PFSENSE_USERNAME}}
              password: {{HOMEPAGE_VAR_PFSENSE_PASSWORD}}

        - PiHole:
            href: https://pihole.robsonhome.cloud
            icon: pihole.png
            description: PiHole DNS
            widget:
              type: pihole
              key: {{HOMEPAGE_VAR_PIHOLE_API_KEY}}

  settings.yaml: |
    title: Dashboard
    theme: dark
    color: slate
    headerStyle: boxed
    providers:
      openweathermap: {{HOMEPAGE_VAR_OPENWEATHERMAP_API_KEY}}
    hideVersion: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Home:
        useEqualHeights: true
        style: column
        icon: mdi-home-analytics
      Network:
        style: row
        columns: 4
        icon: mdi-ethernet
      Media:
        style
      Observability:
        style: column
        icon: mdi-chart-line

  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - search:
        provider: [google]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Welcome back!"
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
