---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        #Networking
        HOMEPAGE_PFSENSE_API_KEY: "{{ .PFSENSE_API_KEY }}"
        HOMEPAGE_PIHOLE_API_KEY: "{{ .HOMEPAGE_PIHOLE_API_KEY }}"

        # Storage
        HOMEPAGE_TRUENAS_API_KEY: "{{ .HOMEPAGE_TRUENAS_API_KEY }}"

        #Cloudflare
        HOMEPAGE_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
        HOMEPAGE_CLOUDFLARED_TUNNEL_KEY: "{{ .CLOUDFLARED_TUNNEL_API_KEY }}"
        HOMEPAGE_CLOUDFLARED_TUNNEL_ID: e901488f-a148-4024-b5a7-8537e7b42287

        #Home automation
        HOMEPAGE_HASSIO_TOKEN: "{{ .HASS_HOMEPAGE_ACCESS_TOKEN }}"

        # Media

        # OpenWeatherMap
        HOMEPAGE_OPENWEATHERMAP_API_KEY: "{{ .HOMEPAGE_OPENWEATHERMAP_API_KEY }}"
        HOMEPAGE_OPENWEATHERMAP_LATITUDE: "{{ .HOMEPAGE_OPENWEATHERMAP_LATITUDE }}"
        HOMEPAGE_OPENWEATHERMAP_LONGITUDE: "{{ .HOMEPAGE_OPENWEATHERMAP_LONGITUDE }}"

  dataFrom:
    - extract:
        key: homepage
    - extract:
        key: pihole
    - extract:
        key: truenas
    - extract:
        key: pfsense
    # - extract:
    #     key: cloudflare
