---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        #Non cluster resources
        HOMEPAGE_PIHOLE_API_KEY: "{{ .api_key }}"
        # HOMEPAGE_CLOUDFLARED_ACCOUNTID: "{{}}"
        # HOMEPAGE_CLOUDFLARED_API_TOKEN: "{{}}"

        #Home automation
        # HOMEPAGE_HASSIO_TOKEN: "{{ .HOMEPAGE_HASSIO_TOKEN }}"

        #Media

  dataFrom:
    - extract:
        key: pihole
    - extract:
        key: cloudflare
