---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        #Networking
        HOMEPAGE_PIHOLE_API_KEY: "{{ .HOMEPAGE_PIHOLE_API_KEY }}"

        # Storage
        HOMEPAGE_TRUENAS_API_KEY: "{{ .HOMEPAGE_TRUENAS_API_KEY }}"

        #Cloudflare
        # HOMEPAGE_CLOUDFLARED_ACCOUNTID: "{{ . }}"
        # HOMEPAGE_CLOUDFLARED_API_TOKEN: "{{}}"

        #Home automation
        # HOMEPAGE_HASSIO_TOKEN: "{{ .HOMEPAGE_HASSIO_TOKEN }}"

        # Media

        # OpenWeatherMap
        HOMEPAGE_OPENWEATHERMAP_API_KEY: "{{ .HOMEPAGE_OPENWEATHERMAP_API_KEY }}"
        HOMEPAGE_OPENWEATHERMAP_LATITUDE: "{{ .HOMEPAGE_OPENWEATHERMAP_LATITUDE }}"
        HOMEPAGE_OPENWEATHERMAP_LONGITUDE: "{{ .HOMEPAGE_OPENWEATHERMAP_LONGITUDE }}"

  dataFrom:
    - extract:
        key: homepage
    # - extract:
    #     key: cloudflare
