---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./authentik.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./democratic-csi.yaml
  - ./descheduler.yaml
  - ./external-secrets.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./longhorn.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./nvidia.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./redis-operator.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./tf-controller.yaml
  - ./tyzbit.yaml
  - ./weaveworks.yaml
