---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: reboot
  service:
    name: reboot
    state: restarted

- name: netplan apply
  service:
    name: netplan
    state: restarted