---
vps_servers:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    tailscale-01:
      ansible_host: 149.28.58.160
      ansible_user: dylan
      #ansible_ssh_pass: "{{ vault_tailscale_user_password }}"
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519

pis:
  vars:
    ansible_user: dylanrobson
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    ns01:
      ansible_host: 10.1.100.2
      dns_title: master

dns-servers:
  vars:
    ansible_user: dylan
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    ns1:
      ansible_host: 10.1.100.51
      bind9_dns_name: master
    ns2:
      ansible_host: 10.1.100.52
      bind9_dns_name: slave
