---
kvmd:
  gpio:
    drivers:
      tes:
        type: tesmart
        host: 10.1.10.205
        port: 5000
      wol_server0:
        type: wol
        mac: 10:62:e5:1a:80:18
      wol_server1:
        type: wol
        mac: 18:60:24:27:27:a7
      wol_server2:
        type: wol
        mac: ac:e2:d3:0d:60:f0
      wol_server3:
        type: wol
        mac: ac:e2:d3:10:d8:25
      wol_server4:
        type: wol
        mac: 10:62:e5:00:4c:12
      wol_server5:
        type: wol
        mac: ac:e2:d3:15:fd:f9
      reboot:
        type: cmd
        cmd: [/usr/bin/sudo, reboot]
      restart_service:
        type: cmd
        cmd: [/usr/bin/sudo, systemctl, restart, kvmd]
    scheme:
      server0_led:
        driver: tes
        pin: 0
        mode: input
      server0_switch:
        driver: tes
        pin: 0
        mode: output
        switch: false
      server1_led:
        driver: tes
        pin: 1
        mode: input
      server1_switch:
        driver: tes
        pin: 1
        mode: output
        switch: false
      server2_led:
        driver: tes
        pin: 2
        mode: input
      server2_switch:
        driver: tes
        pin: 2
        mode: output
        switch: false
      server3_led:
        driver: tes
        pin: 3
        mode: input
      server3_switch:
        driver: tes
        pin: 3
        mode: output
        switch: false
      server4_led:
        driver: tes
        pin: 4
        mode: input
      server4_switch:
        driver: tes
        pin: 4
        mode: output
        switch: false
      server5_led:
        driver: tes
        pin: 5
        mode: input
      server5_switch:
        driver: tes
        pin: 5
        mode: output
        switch: false
      wol_server0:
        driver: wol_server0
        pin: 0
        mode: output
        switch: false
      wol_server1:
        driver: wol_server1
        pin: 0
        mode: output
        switch: false
      wol_server2:
        driver: wol_server2
        pin: 0
        mode: output
        switch: false
      wol_server3:
        driver: wol_server3
        pin: 0
        mode: output
        switch: false
      wol_server4:
        driver: wol_server4
        pin: 0
        mode: output
        switch: false
      wol_server5:
        driver: wol_server5
        pin: 0
        mode: output
        switch: false
      reboot_button:
        driver: reboot
        pin: 0
        mode: output
        switch: false
      restart_service_button:
        driver: restart_service
        pin: 0
        mode: output
        switch: false
    view:
      table:
        - ["TESMART Switch"]
        - []
        - [
            "#Kube-01",
            server0_led,
            server0_switch | Switch,
            "wol_server0 | Wol",
          ]
        - ["#Kube-02", server1_led, server1_switch|Switch, "wol_server1 | Wol"]
        - ["#Kube-03", server2_led, server2_switch|Switch, "wol_server2 | Wol"]
        - ["#Kube-04", server3_led, server3_switch|Switch, "wol_server3 | Wol"]
        - ["#Kube-05", server4_led, server4_switch|Switch, "wol_server4 | Wol"]
        - ["#Kube-06", server5_led, server5_switch|Switch, "wol_server5 | Wol"]
        - [
            "#PiKVM",
            "pikvm_led|green",
            "restart_service_button|confirm|Service",
            "reboot_button|confirm|Reboot",
          ]
