# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:eQ3CclO5P8EYk9UhYYfD0AIV4fFCCs7jGiTnhKYkhgYwW3aPjaFamg==,iv:I2HvvtNn9/EVlYnxpDin9gfscrRjy45wbmUc/e9jHbM=,tag:IQAkmKidh5tj5VayPjkUlQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age109xxk5j8q09kprdd5wta9fw7nwpz8t95phq49eclrefjy3zjncmqa9lgtk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYldWaXkyMUp5alRRa1NC
        L0VUc05NZzU1Q2E5TFQ1UWFwL0l3NFNwYVNRCjB0bnJCTlowVWZhcUlrN3MzbzBJ
        MWxwb0JHZmg0NGJUT2lrSnlNd0pNVk0KLS0tIFNOdmxFVSt5aFEyTHFMRXRmNFNN
        d0xOdHN5RTVzQTd4ckZYTS9PZFZJQWsKZ7StP1tDs9+yYallaggiB4KT9RDb2b7b
        EJR7+RupW2MwTUuEMauGakTXqcKuoJq2j35uLlrw3RBkqi2cNl2v/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-12T14:58:31Z"
  mac: ENC[AES256_GCM,data:ie15I9dmH4yKANm3UfD4eQDYGAVqEBLslJFWE1lOxR8r7POpwLSX8GB3YPOvPVOyG9YiFuR/sbsI2vVujaJOBgbNPheQWf28yQ56kAE6nNaQpQykpRzBub7yzzBs1YPzXlXWesGuOBj2nO/5Fgp30E/SClLTpRDp2qliCwr86M4=,iv:OmEqux/lUd/tBuvbpTvEyQYH01NboB71ax42BE/1neg=,tag:vtuG2nwt3n286h8mNgSkqw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
