---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Setup /etc/hosts
  template:
    src: templates/hosts.yaml.j2
    dest: /etc/hosts

- name: Remove symlink to /etc/resolv.conf
  command: rm /etc/resolv.conf
  when: ansible_distribution == 'Ubuntu'

- name: Create /etc/resolv.conf
  copy:
    src: files/resolv.conf
    dest: /etc/resolv.conf
    mode: preserve
  when: ansible_distribution == 'Ubuntu'
# - name: Check if old netplan is present
#   stat:
#     path: /etc/netplan/50-cloud-init.yaml
#   register: netplan

# - name: Backup and Remove netplan currently on the system
#   command: cp 50-cloud-init.yaml 50-cloud-init.yaml.bak && rm 50-cloud-init.yaml
#   when: ansible_distribution == 'Ubuntu' && netplan.stat.exists == True

- name: Configure netplan
  template:
    src: templates/01-netplan-all.yaml.j2
    dest: /etc/netplan/01-netplan-all.yaml
  when: ansible_distribution == 'Ubuntu'
# - name: Apply netplan
#   command: netplan apply
#   when: ansible_distribution == 'Ubuntu'

# - name: Restart networkd
#   systemd:
#     name: systemd-networkd
#     state: restarted
#   when: ansible_distribution == 'Ubuntu'
