---
# - name: Set hostname
#   hostname:
#     name: "{{ ansible_hostname }}"
#   become: true

# - name: Setup /etc/hosts
#   template:
#     src: templates/hosts.yaml.j2
#     dest: /etc/hosts
#   become: true

- name: Set network interfaces configuration
  template:
    src: templates/interfaces.yaml.j2
    dest: /etc/network/interfaces

- name: systemctl restart networking
  systemd:
    name: networking
    state: restarted
  become: true
