---
- name: Set hostname
  hostname:
    name: "{{ ansible_hostname }}"
  become: true

- name: Setup /etc/hosts
  template:
    src: templates/hosts.yaml.j2
    dest: /etc/hosts
  become: true

- name: enable 8021q module
  modprobe:
    name: 8021q
  become: true

- name: Add 8021q module to /etc/modules
  lineinfile:
    path: /etc/modules
    line: 8021q
  become: true

- name: Install vlan package
  apt:
    name: vlan
    state: present
  become: true

- name: Set network interfaces configuration
  template:
    src: templates/interfaces.yaml.j2
    dest: /etc/network/interfaces

- name: systemctl restart networking
  systemd:
    name: networking
    state: restarted
  become: true
