- name: Install nfs-common if not installed
  apt:
    name: nfs-common
    state: present

- name: System Configuration | NFS
  copy:
    src: files/nfsmount.conf
    dest: /etc/nfsmount.conf
    owner: root
    group: root
    mode: "0644"

- name: Mount Docker NFS Share
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: nfs
    opts: "{{ item.opts }}"
    state: mounted
  with_items: "{{ docker_nfs_mounts }}"
