- name: Install nfs-common if not installed
  apt:
    name: nfs-common
    state: present

- name: System Configuration | NFS
  copy:
    src: files/nfsmount.conf
    dest: /etc/nfsmount.conf
    owner: root
    group: root
    mode: "0644"

- name: Mount Docker NFS Share
  mount:
    src: 10.101.101.210:/mnt/tank/nfs/docker-volumes
    path: /mnt/docker-volumes
    fstype: nfs
    opts: "rw,sync,hard"
    state: mounted
