- name: User Configuration | SSH keys
  authorized_key:
    user: "{{ me.user }}"
    key: "https://github.com/{{ github_username }}.keys"
    state: present

- name: Update sshd_config
  copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644

- name: Restart sshd
  service:
    name: sshd
    state: restarted
    enabled: true
  become: true
