- name: Update & upgrade apt
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: Install vlan package
  apt:
    name: vlan
    state: present

- name: enable vlan
  command: modprobe 8021q

- name: Setup VLANs in Netplan
  template:
    src: templates/01-netplan-all.yaml.j2
    dest: /etc/netplan/01-netplan-all.yaml
  become: true

- name: Apply Netplan
  command: netplan apply
  become: true
