---
- name: Create user if not exists
  user:
    name: "{{ me.user }}"
    shell: /bin/bash
    password: ""
  become: true

- name: Add user to visudo
  lineinfile:
    path: /etc/sudoers
    line: "{{ me.user }} ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"
  become: true

- name: Grant user ownership of /home/{me.user}
  file:
    path: "/home/{{ me.user }}"
    owner: "{{ me.user }}"
    group: "{{ me.user }}"
    state: directory
  become: true
