# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.1.20.120:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.1.20.120"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-0"
    ipAddress: "10.1.20.10"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/a0b4991356a74f14e884e8b9192ac3864397894fa5223317098564de42ce0a0f
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "10:62:e5:00:4c:12"
        dhcp: false
        addresses:
          - "10.1.20.10/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.1.20.1"
        mtu: 1500
        vip:
          ip: "10.1.20.120"
  - hostname: "k8s-1"
    ipAddress: "10.1.20.11"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/a0b4991356a74f14e884e8b9192ac3864397894fa5223317098564de42ce0a0f
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "18:60:24:27:27:a7"
        dhcp: false
        addresses:
          - "10.1.20.11/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.1.20.1"
        mtu: 1500
        vip:
          ip: "10.1.20.120"
  - hostname: "k8s-2"
    ipAddress: "10.1.20.12"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/a0b4991356a74f14e884e8b9192ac3864397894fa5223317098564de42ce0a0f
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "ac:e2:d3:0d:60:f0"
        dhcp: false
        addresses:
          - "10.1.20.12/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.1.20.1"
        mtu: 1500
        vip:
          ip: "10.1.20.120"
  - hostname: "k8s-3"
    ipAddress: "10.1.20.13"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/a0b4991356a74f14e884e8b9192ac3864397894fa5223317098564de42ce0a0f
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "ac:e2:d3:10:d8:25"
        dhcp: false
        addresses:
          - "10.1.20.13/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.1.20.1"
        mtu: 1500
  - hostname: "k8s-4"
    ipAddress: "10.1.20.14"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/a0b4991356a74f14e884e8b9192ac3864397894fa5223317098564de42ce0a0f
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "ac:e2:d3:15:fd:f9"
        dhcp: false
        addresses:
          - "10.1.20.14/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.1.20.1"
        mtu: 1500
  - hostname: "k8s-5"
    ipAddress: "10.1.20.15"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/a0b4991356a74f14e884e8b9192ac3864397894fa5223317098564de42ce0a0f
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "10:62:e5:1a:80:18"
        dhcp: false
        addresses:
          - "10.1.20.15/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.1.20.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

