---
- name: Clean and mount SSDs to Longhorn path
  hosts: longhorn_nodes
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:

    - name: Clean disks and format + mount
      ignore_errors: true
      block:
        - name: wipe (wipefs)
          command: "wipefs -a {{ ssd_drive }}"

        - name: wipe (sgdisk)
          command: "sgdisk --zap-all {{ ssd_drive }}"

        - name: wipe (dd)
          command: "dd if=/dev/zero of={{ ssd_drive }} bs=1M count=100 oflag=direct,dsync"

        - name: wipe (partprobe)
          command: "partprobe {{ ssd_drive }}"

        - name: format disks ext4
          filesystem:
            fstype: ext4
            dev: "{{ ssd_drive }}"

        - name: Get UUID of disks (blkid)
          command: "blkid -s UUID -o value {{ ssd_drive }}"
          register: blkid

        - name: Create mount point for longhorn
          file:
            path: "{{ longhorn_mount_point }}"
            state: directory
            mode: 0755

        - name: Mount the disks to the longhorn mount point
          mount:
            path: "{{ longhorn_mount_point }}"
            src: "UUID={{ blkid.stdout }}"
            fstype: ext4
            state: mounted
            opts: defaults
