include "/etc/bind/named.conf.key";

controls {
    inet 127.0.0.1 port 953
    allow { 127.0.0.1; } keys { "tsig-key"; };
};

acl trusted-networks {
  10.1.1.0/24;
  10.1.10.0/24;
  10.1.20.0/24;
  10.1.30.0/24;
  10.1.33.0/24;
  10.1.40.0/24;
};

acl lan-prod-1 {
  10.10.0.0/16;
};

options {
  forwarders {
    10.1.1.1;
  };
  allow-query { 127.0.0.1; trusted-networks; };
};

zone "robsonhome.cloud" IN {
  type master;
  file "/etc/bind/robsonhome.cloud.zone";
  update-policy { grant tsig-key zonesub any; };
};
