---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name node-exporter
spec:
  staticConfigs:
    - targets:
        - 10.1.1.1:9100
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: minio
spec:
  scheme: HTTPS
  staticConfigs:
    - targets: ['s3.robsonhome.cloud:9000']
  metricsPath: /minio/v2/metrics/cluster
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name pikvm
spec:
  staticConfigs:
    - targets: ['pikvm.robsonhome.cloud']
  metricsPath: /api/export/prometheus/metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
# apiVersion: monitoring.coreos.com/v1alpha1
# kind: ScrapeConfig
# metadata:
#   name: &name technitium-dns
# spec:
#   staticConfigs:
#     - targets: ['ns1.robsonhome.cloud']
#   metricsPath: /metrics
#   relabelings:
#     - action: replace
#       targetLabel: job
#       replacement: *name
# ---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
# apiVersion: monitoring.coreos.com/v1alpha1
# kind: ScrapeConfig
# metadata:
#   name: &name zigbee-controller
# spec:
#   staticConfigs:
#     - targets: ['zcontroller.robsonhome.cloud']
#   metricsPath: /metrics
#   relabelings:
#     - action: replace
#       targetLabel: job
#       replacement: *name
