---
- name: Install frigate docker compose
  copy:
    src: files/docker-compose.yaml
    dest: "{{ docker_volumes_directory }}/frigate/docker-compose.yaml"
    owner: "{{ me.user }}"
    group: "docker"
    mode: "0644"
  become: true

- name: Create frigate directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ me.user }}"
    group: "docker"
    mode: "0755"
  loop:
    - "{{ frigate.config_directory }}"
    - "{{ frigate.data_directory }}"

- name:
