---
- name: Check if pre-build Apex driver is installed
  command: "lsmod | grep apex"
  register: apex_driver
  ignore_errors: true

- name: Add Debian repository
  command: "echo 'deb https://packages.cloud.google.com/apt coral-edgetpu-stable main' | sudo tee /etc/apt/sources.list.d/coral-edgetpu.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -"
  when: "ansible_distribution == 'Debian' and apex_driver.rc == 0"
  become: true

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install PCIe driver & Edge TPU runtime packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "gasket-dkms"
    - "libedgetpu1-std"

- name: Update udev rule & add user to 'apex' group
  command: sh -c "echo 'SUBSYSTEM==\"apex\", MODE=\"0660\", GROUP=\"apex\"' >> /etc/udev/rules.d/65-apex.rules"'
  become: true

- name: Add user to 'apex' group
  user:
    name: "{{ me.user }}"
    groups: apex
    append: yes
  become: true

- name: Reboot server
  reboot:
  become: true

- name: Verify accelerator module is detected
  command: "lspci -nn | grep 089a"
  register: accelerator
  ignore_errors: true

- name: print accelerator
  debug:
    var: accelerator

- name: Verify PCIe driver is loaded
  command: "ls /dev/apex0"
  register: pcie_driver
  ignore_errors: true

- name: print pci_device
  debug:
    var: pci_device
