---
- name: restart wireguard service
  service:
    name: wg-quick@wg0
    enabled: 'true'
    state: restarted

- name: start wireguard service
  service:
    name: wg-quick@wg0
    enabled: 'true'
    state: started

- name: enable ufw
  service:
    name: ufw
    enabled: 'true'
    state: started

- name: Restart sshd
  service:
    name: sshd
    state: restarted

