- name: Cluster Networking
  hosts: kubernetes
  become: true
  gather_facts: true
  tasks:
    - name: Configure DNS
      block:
        - name: Configure DNS
          include_tasks:
            file: tasks/dns.yaml
            # when: ansible_distribution == 'Ubuntu'

        # - name: Configure DNS
        #   lineinfile:
        #     dest: /etc/systemd/resolved.conf
        #     regexp: '^#?DNS='
        #     line: 'DNS=

        - name: Reboot
          reboot:
            msg: Rebooting nodes
            reboot_timeout: 3600
