---
- hosts: kubernetes
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Kubeconfig
      include_tasks: tasks/kubeconfig.yaml
      vars:
        repository_base: "{{ lookup('pipe', 'git rev-parse --show-toplevel') }}"
