timezone: America/New_York
github_username: "DylansDecoded"
# HACK: Some of the hostnames aren't valid dict keys
hostname_slug: "{{ ansible_hostname | replace('-', '_') }}"
truenas_server_ip: 10.101.101.210
package_list:
  - curl
  - iperf3
  - fail2ban
  - restic
  - wireguard
  - net-tools
  - wget
  - python3
  - python3-pip
  - rsyslog
  - nfs-common
  - open-iscsi


