---
gateway_hostname: wg-gateway


# Packages to install
package_list:
  - curl
  - iperf3
  - fail2ban
  - restic
  - wireguard
  - net-tools
  - wget
  - python3
  - python3-pip
  - rsyslog

### UFW Rules
ufw:
  - comment: 'ssh'
    rule: 'allow'
    port: '22'
    proto: 'any'
    route: 'no'
  - comment: 'reverse proxy'
    rule: 'allow'
    port: '80'
    proto: 'tcp'
    route: 'no'
  - comment: 'reverse proxy'
    rule: 'allow'
    port: '443'
    proto: 'tcp'
    route: 'no'
  - comment: 'iperf'
    rule: 'allow'
    port: '5201'
    proto: 'tcp'
    route: 'no'
  - comment: 'rsyslog'
    rule: 'allow'
    port: '{{ secret_rsyslog_port }}'
    proto: 'tcp'
    route: 'no'
  - comment: 'wireguard'
    rule: 'allow'
    port: '51820'
    proto: 'udp'
    route: 'no'
  - comment: 'wireguard tunnel'
    rule: 'allow'
    port: '51282'
    proto: 'udp'
    route: 'no'
  - comment: 'portainer'
    rule: 'allow'
    port: '9001'
    proto: 'tcp'
    route: 'no'
  - comment: 'tailscale adapter'
    rule: 'allow'
    interface: tailscale0
    direction: in
    proto: 'any'
    route: 'no'