---

# - hosts: all
#   become: yes
#   roles:
#     - base

# - hosts: raspberries
#   become: yes
#   roles:
#     - geerlingguy.docker
#     - docker_cleanup

- hosts: adguardhome_servers
  become: yes
  roles:
    - adguardhome
  
    
  
