# network-attachment-definition.yaml
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: netattach-iot
  namespace: network
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "eno1.40",
      "ipam": {
        "type": "static",
        "routes": [
          { "dst": "10.1.0.0/16", "gw": "10.1.40.1" }
        ]
      }
    }
