---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: networking
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pihole
  namespace: networking
subsets:
  - addresses:
      - ip: 10.1.100.53
    ports:
      - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  namespace: networking
  annotations:
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # nginx.ingress.kubernetes.io/rewrite-target: /admin
spec:
  ingressClassName: internal
  rules:
    - host: &host pihole.robsonhome.cloud
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: pihole
                port:
                  number: 80
  tls:
    - hosts:
        - *host
