---
apiVersion: v1
kind: Service
metadata:
  name: proxmox
spec:
  ports:
    - protocol: TCP
      port: 8006
      name: https
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox
subsets:
  - addresses:
      - ip: 10.1.10.51
      - ip: 10.1.10.52
      - ip: 10.1.10.53
    ports:
      - port: 8006
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxmox
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  # labels:
  #   app.kubernetes.io/name: proxmox
  #   app.kubernetes.io/instance: proxmox
spec:
  ingressClassName: internal
  rules:
    - host: &host pve.robsonhome.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxmox
                port:
                  name: https
  tls:
    - hosts:
        - *host
