container_user:
  id: 3000
  name: containeruser

docker_compose_file_mask: "664"
docker_compose_directoy_mask: "775"

docker_update_command: docker compose pull && docker compose down --remove-orphans && docker compose up rm && docker compose up -d

### UFW Rules
ufw:
  - comment: 'dns'
    rule: 'allow'
    port: '53'
    proto: 'udp'
    route: 'no'
  - comment: 'dns'
    rule: 'allow'
    port: '53'
    proto: 'tcp'
    route: 'no'
  - comment: 'dns-over-tls'
    rule: 'allow'
    port: '853'
    proto: 'tcp'
    route: 'no'
  - comment: 'dns-over-tls'
    rule: 'allow'
    port: '853'
    proto: 'udp'
    route: 'no'
  - comment: 'ssh'
    rule: 'allow'
    port: '22'
    proto: 'any'
    route: 'no'
  - comment: 'reverse proxy'
    rule: 'allow'
    port: '80'
    proto: 'tcp'
    route: 'no'
  - comment: 'reverse proxy'
    rule: 'allow'
    port: '443'
    proto: 'tcp'
    route: 'no'
  - comment: 'iperf'
    rule: 'allow'
    port: '5201'
    proto: 'tcp'
    route: 'no'
  - comment: 'wireguard'
    rule: 'allow'
    port: '51821'
    proto: 'udp'
    route: 'no'
  - comment: 'wireguard tunnel'
    rule: 'allow'
    port: '51282'
    proto: 'udp'
    route: 'no'
  - comment: 'portainer'
    rule: 'allow'
    port: '9001'
    proto: 'tcp'
    route: 'no'
  - comment: 'tailscale adapter'
    rule: 'allow'
    interface: tailscale0
    direction: in
    proto: 'any'
    route: 'no'