---
apiVersion: v1
kind: Service
metadata:
  name: omada-controller
  namespace: network
spec:
  ports:
    - protocol: TCP
      port: 8843
---
apiVersion: v1
kind: Endpoints
metadata:
  name: omada-controller
  namespace: network
subsets:
  - addresses:
      - ip: 10.1.10.200
    ports:
      - port: 8843
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omada
  namespace: network
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
    # nginx.ingress.kubernetes.io/proxy-set-header: "Host $http_host:8843"
    # nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "https://omada.robsonhome.cloud:8043"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://omada.robsonhome.cloud/login"
spec:
  ingressClassName: internal
  rules:
    - host: &host omada.robsonhome.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: omada-controller
                port:
                  number:
  tls:
    - hosts: [*host]