---
apiVersion: v1
kind: Service
metadata:
  name: truenas
  namespace: network
  labels:
    app.kubernetes.io/name: truenas
    app.kubernetes.io/instance: truenas
spec:
  type: ExternalName
  externalName: truenas.
  ports:
    - name: http
      port: &port 80
      protocol: TCP
      targetPort: *port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: truenas
  namespace: network
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: internal
  rules:
    - host: &host truenas.robsonhome.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: truenas
                port:
                  number: 80
  tls:
    - hosts:
        - *host
