---
- name: Check for cloudinit netplan file
  stat:
    path: /etc/netplan/50-cloud-init.yaml
  when: ansible_distribution == "Ubuntu"
  register: cloudinit_netplan

# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}

- name: Delete cloudinit netplan file
  file:
    path: /etc/netplan/50-cloud-init.yaml
    state: absent
  when: cloudinit_netplan.stat.exists and ansible_distribution == "Ubuntu"

- name: Comment out update_etc_hosts in /etc/cloud/cloud.cfg
  lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: "^update_etc_hosts: true"
    line: "#update_etc_hosts: true"
    state: present
  when: cloudinit_netplan.stat.exists

- name: Create new netplan file
  template:
    src: etc/netplan/01-network-manager-all.yaml.j2
    dest: /etc/netplan/01-network-manager-all.yaml
    owner: root
    group: root
    mode: 0644

- name: Apply netplan configuration
  command: netplan apply

- name: Update /etc/hosts
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: Remove /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

- name: Create new /etc/resolv.conf
  template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
